### ISSUE TITLE
Space Engine Follow Pet

### ISSUE THREAD

**Issue by nervkil** [Helediron/dualuniverse#1]
I would like to make the "moose" work inside a ship while in space. I see the script you wrote requires atmo, what would be needed to modify it to use space engines so I could get it to bumble around inside an enclosed area inside a ship while in space? Would this be quite difficult? Curious to know what you think would be needed to achieve this functionality. Thanks for any assistance you could provide!

**Comment by Helediron** [comment]
I believe you can switch the hover to vertical booster and atmo engines to space engines. Script doesn't need any changes because of that. They act the same way.
Hovers, vboosters and telemeters can act as distance detectors. If you use vbooster for lift, link that to teledown slot in script and it works also as distance detector.

**Comment by nervkil** [comment]
ok great. I'll give it a shot. thanks for the response!
